### ISSUE TITLE
Schedule is empty on first load

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/clc-conference-app#31] opened 2019-03-26 15:42 UTC
Close the app
Load the app
Click Schedule

![Image from iOS (2)](https://user-images.githubusercontent.com/11731079/55011320-b8d1ac80-4fb3-11e9-9fe4-711f38a2683a.png)

It should be showing monday content.
When you click on Tuesday and come back to monday, the content is there.

**Comment by conrad-vanl** [comment] 2019-03-26 15:58
This is just a loading state, right? the schedule items end up popping in if you leave this open for a second?

**Comment by frizman21** [comment] 2019-03-26 17:00
Negative - still waiting.

**Comment by conrad-vanl** [comment] 2019-03-28 01:30
I cannot reproduce on newest build from my end. I upgraded the component that drives the tab view on this screen, and I believe that fixed it. Closing for now. Closed in #40 and #33

**Closed as completed by conrad-vanl** 2019-03-28 01:30 UTC
Labels: bug

**Comment by frizman21** [comment] 2019-03-28 02:20
confirmed.
